spring:
  data:
    mongodb:
      database:
        uri: mongodb://localhost:27017/demodb
        port: 27017
        auto-index-generation: true
logging:
  level:
    root: INFO
#nell'uri si mette mongodb://localhost:portaEsterna/nomedb
