spring:
  data:
    mongodb:
        uri: mongodb://localhost:27017/ozigiggin
        database: ozigiggin
        auto-index-creation: true
logging:
  level:
    root: INFO
#nell'uri si mette mongodb://localhost:portaEsterna/nomedb
